// <auto-generated />
namespace SpaceWay.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class m73 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m73));
        
        string IMigrationMetadata.Id
        {
            get { return "201906212024450_m73"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
